package net.activitywatch.android.watcher.utils

const val PAGE_VISIT_TIME_MILLIS = 5000L
const val PAGE_MAX_WAIT_TIME_MILLIS = 10000L
const val MAX_CONDITION_WAIT_TIME_MILLIS = 10000L

const val CUSTOM_TABS_SERVICE_TIMEOUT_MILLIS = 30000L
const val NAVIGATION_STARTED_TIMEOUT_MILLIS = 10000L